set -g default-terminal "tmux-256color"
set -ag terminal-overrides "xterm-256color:RGB"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h 

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r C-h previous-window
bind -r C-l next-window

bind -r m resize-pane -Z

set -g mouse on

set-window-option -g mode-keys vi
set-option -g status-style bg=default
set-option -g status on
set-option -g status-interval 1
set-option -g status-justify centre
set-option -g status-keys vi
set-option -g status-position bottom
set-option -g status-style fg=colour136
set-option -g status-left-length 20
set-option -g status-left-style default
set-option -g status-left "#[fg=green]#H"
set-option -g status-right-length 140
set-option -g status-right-style default
set -g status-right '#[fg=white,bg=default]%a #(TZ="Asia/Kolkata" date +%%H:%%M:%%S)'
set-option -ag status-right " #[fg=blue]%b-%d-%Y"
set-window-option -g window-status-style fg=colour244
set-window-option -g window-status-current-style fg=colour255

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10
set-option -g status-position top
set -g mouse on
set-option -wg automatic-rename off
set -g base-index 1
set -g pane-base-index 1

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sensible

run '~/.tmux/plugins/tpm/tpm

